Feat/modal
MarinaKrasnov/staff-motivation pull request #4
Opened 2023-08-15 13:03 UTC by Malaglovets

Верстка модального окна. Логики нет, так как далее пока не понятно куда перенаправлять будет. Так же пропс Message не писал, так  как я понял из макета, что текст всегда при успешном изменении пароля один и тот же. Вообщем пиши что нужно исправить.

2023-08-15 17:52 UTC, MarinaKrasnov requested changes

2023-08-15 17:52 UTC, MarinaKrasnov commented on README.md
> +# Getting Started hello
а это еще для чего?

2023-08-15 17:52 UTC, MarinaKrasnov commented on public/index.html
> +		<div id="modals"></div>
для чего это?
лишнее

2023-08-15 17:52 UTC, MarinaKrasnov commented on src/components/App/App.jsx
> +		<div className='App'>
Код в app для упрощения заливки мы обрамляем комментариями имени и кратким описанием функционала кода если из названия не ясно.

2023-08-15 17:52 UTC, MarinaKrasnov commented on src/components/Modal/Modal.jsx
> +function Modal() {
модалки будет уже как минимум две, подумай как ты сможешь переиспользовать компонент, тебя ждет еще одна задача на канбан доске

2023-08-15 17:54 UTC, MarinaKrasnov commented
ты делал npm commit run?

2023-08-15 18:18 UTC, Malaglovets commented on README.md
> +# Getting Started hello
Это я как раз и пробовал npm commit run и по ошибки запушил

2023-08-15 18:19 UTC, Malaglovets commented on public/index.html
> +		<div id="modals"></div>
Это для того, что бы модальное окно появлялось, но как я понимаю у нас не совсем модалка, поэтому уберу

2023-08-15 18:19 UTC, Malaglovets commented on src/components/App/App.jsx
> +		<div className='App'>
Ок, допишу

2023-08-15 18:20 UTC, Malaglovets commented on src/components/Modal/Modal.jsx
> +function Modal() {
Ок

2023-08-19 09:46 UTC, MarinaKrasnov requested changes

2023-08-19 09:46 UTC, MarinaKrasnov commented on src/components/Modal/Modal.jsx
> +import logo from '../images/CircleWavyCheck.png';
картинка мутная, используй лучше svg

2023-08-19 09:46 UTC, MarinaKrasnov commented on src/App.test.js
>  test('renders learn react link', () => {
для чего этот тест?

2023-08-19 09:46 UTC, MarinaKrasnov commented on src/components/App/App.jsx
> +		<div className='App'>
я не вижу исправлении что я просила

2023-08-19 09:48 UTC, MarinaKrasnov commented
да и ссылка у тебя идет на main- поправь на signin

2023-08-19 10:18 UTC, Malaglovets commented on src/components/Modal/Modal.jsx
> +import logo from '../images/CircleWavyCheck.png';
Исправил

2023-08-19 10:20 UTC, Malaglovets commented on src/App.test.js
>  test('renders learn react link', () => {
Он не нужен и не рабочий, удаляю. Это шаблон который был изначально

2023-08-19 11:38 UTC, Malaglovets commented
Что касается исправлений, все что обсуждали, я исправил:
1. Добавил возможность открывать попап.
2. Добавить временный серый фон, что бы был виден попап.
3. Добавил переход на другую страницу.
4. Убрал красную обводку.
Более мы ничего не обсуждали. Если нужны еще исправления, напиши их, что бы как в прошлый раз, несколько дней мы не решали разные проблемы.

2023-08-22 21:39 UTC, Egornikolaev97 commented
Привет!
для кнопки нужно пару стилей дописать:
border: none;
border-radius: 3px;
font-weight: 500 
а то у тебя кнопка с обводкой получилась и с острыми углами )). В остальном по верстке нет вопросов 
![image](https://github.com/MarinaKrasnov/staff-motivation/assets/85133780/8f6e00b3-c56f-499d-82ed-31acfe387784)

2023-08-23 12:25 UTC, AnnaKharatova approved these changes

2023-08-23 12:25 UTC, merged